// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Ticket_Booking_System.Data;

namespace Online_Ticket_Booking_System.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220614221617_Add TransportCompanies table")]
    partial class AddTransportCompaniestable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Online_Ticket_Booking_System.Models.TransportCompany", b =>
                {
                    b.Property<int>("TCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TCID");

                    b.ToTable("TransportCompanies");
                });

            modelBuilder.Entity("Online_Ticket_Booking_System.Models.Vehicles", b =>
                {
                    b.Property<int>("VechilesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TCID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VechilesID");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
